# Generated by Django 5.1 on 2024-08-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255)),
                ('car_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_image', models.ImageField(upload_to='car_images/')),
                ('launch_date', models.DateField()),
                ('on_road_price', models.CharField(max_length=255)),
            ],
        ),
    ]
