# Generated by Django 5.1 on 2024-08-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_featuredcars_featuredcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255)),
                ('car_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_image', models.ImageField(upload_to='car_images/')),
                ('on_road_price', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255)),
                ('car_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_image', models.ImageField(upload_to='car_images/')),
                ('on_road_price', models.CharField(max_length=255)),
            ],
        ),
    ]
