# Generated by Django 5.1 on 2024-08-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_popularcar_upcomingcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UppcomingCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255)),
                ('start_car_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('end_car_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('type', models.CharField(max_length=255)),
                ('car_image', models.ImageField(upload_to='car_images/')),
                ('on_road_price', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='UpcomingCar',
        ),
    ]
